### ISSUE TITLE
Idea: Incluir un Cronograma

### ISSUE THREAD

**Issue by andrespavez** [mave007/lacnog-dns-wg#1]
# Cronograma
Estas fechas están sujetas a cambio en función de consideraciones operacionales. 

- [X] **27 de Octubre de 2016:** Una nueva KSK fue generada en la instalación Este de administración de llaves de ICANN.
- [X] **02 de Febrero de 2017:** La nueva KSK fue replicada en la instalación Oeste de administración de llaves de ICANN.
- [X] **03 de Febrero de 2017:**  El anclaje de la zona raíz (Trust Anchors) fue actualizado para incluir la nueva KSK.
- [X] **27 de Abril de 2017:** Se firmo el primer conjunto de llaves que contienen la nueva KSK.
- [ ] **11 de Julio de 2017:** Publicación de la nueva KSK en el DNS como parte del DNSKEY RRset que es firmado por la antigua KSK.
- [ ] **19 de Septiembre de 2017:** Aumento del tamaño las respuesta DNSKEY de los  servidores de la zona raíz.
- [ ] **11 de Octubre de 2017:** La nueva KSK comienza a firmar el conjunto de llaves de la zona raíz _(el evento de rotación de la KSK)._
- [ ] **11 de Enero de 2018:** Revocación de la antigua KSK.
- [ ] **22 de Marzo de 2018:** Último día en que la antigua KSK aparece en la zona raíz.
- [ ] **Mayo de 2018:** Eliminación de la antigua KSK en la instalación Este de administración de llaves de ICANN.
- [ ] **Agosto de 2018:** Eliminación de la antigua KSK en la instalación Oeste de administración de llaves de ICANN.

**Comment by huguei** [comment]
Gracias! Actualizaré el rotacion_ksk.md con estas fechas.
